### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by kenyon** [SecurityCentral/classification-banner-fork#4]
Commit 85f87878913554a90caa163ff2d088fbf0d8e551 causes `AttributeError: 'bool' object has no attribute 'lower'` when running classification-banner.

This is on RHEL 7 with Python 2.7.5.

Full traceback:

```
Traceback (most recent call last):
  File "/usr/bin/classification-banner", line 8, in <module>
    banner.main()
  File "/usr/lib/python2.7/site-packages/classification_banner/banner.py", line 372, in main
    run = Display_Banner()
  File "/usr/lib/python2.7/site-packages/classification_banner/banner.py", line 225, in __init__
    self.config = self.configure()
  File "/usr/lib/python2.7/site-packages/classification_banner/banner.py", line 270, in configure
    parser.add_argument("--disable-esc", default=strtobool(defaults["esc"]),
  File "/usr/lib64/python2.7/distutils/util.py", line 334, in strtobool
    val = string.lower(val)
  File "/usr/lib64/python2.7/string.py", line 226, in lower
    return s.lower()
AttributeError: 'bool' object has no attribute 'lower'
```

My `/etc/classification-banner/banner.conf`:

```
[global]
message = UNCLASSIFIED
foreground = #FFFFFF
background = #007A33
sys_info = True
opacity = 0.30
```

**Comment by kenyon** [comment]
The problem occurs because lines 250 through 257 set the defaults to booleans instead of strings like strtobool is expecting, and when you don't have every value specified in banner.conf, it uses those values. Changing the Trues and Falses to strings in lines 250 through 257 fixes the program.
