### ISSUE TITLE
Centos 8 or Rhel 8 not working

### ISSUE THREAD

**Issue by ozzbrian** [SecurityCentral/classification-banner-fork#6]
Wondering if anyone got this working on Cento8 or Rhel 8 I keep getting these errors

Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/classification-banner", line 4, in <module>
    __import__('pkg_resources').run_script('classification-banner==1.7.0', 'classification-banner')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/classification_banner-1.7.0-py3.6.egg/EGG-INFO/scripts/classification-banner", line 8, in <module>
  File "/usr/local/lib/python3.6/site-packages/classification_banner-1.7.0-py3.6.egg/classification_banner/banner.py", line 390, in main
  File "/usr/local/lib/python3.6/site-packages/classification_banner-1.7.0-py3.6.egg/classification_banner/banner.py", line 238, in __init__
  File "/usr/local/lib/python3.6/site-packages/classification_banner-1.7.0-py3.6.egg/classification_banner/banner.py", line 261, in configure
  File "/usr/lib64/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'global

**Comment by redhatrises** [comment]
A couple of questions:

1. Does `/etc/classification-banner/banner.conf` exist?
2. Does it work when you change `conf.items("global")` to `conf.items()`?

**Comment by ozzbrian** [comment]
Yes I was able to clear the etc/classification-banner/banner.conf issue. I tryied your sugestion to change conf.items("global") to conf.items() and still having same problem
